### ISSUE TITLE
Vergleiche zwischen 2013 und 2017 sollten relativ sein

### ISSUE THREAD

**Issue by torfsen** [CodeforKarlsruhe/wahlkarte#5]
Wenn wir die Ergebnisse von 2013 und 2017 vergleichen, dann sollte das nicht auf Basis absoluter Stimmenzahlen passieren, sondern auf Basis der relativen Prozentzahlen. Andernfalls wird die Analyse durch Schwankungen in der Zahl der Wahlberechtigten und in der Wahlbeteiligung verfälscht.

Betroffen sind davon die Ansichten [Wechselwähler](https://codeforkarlsruhe.github.io/wahlkarte/#wechselwaehler) und [Größte Änderung](https://codeforkarlsruhe.github.io/wahlkarte/#aenderung).

**Comment by hcorinna** [comment]
Stimmt, wobei ich die [Wechselwähler*innen](https://codeforkarlsruhe.github.io/wahlkarte/#wechselwaehler) nicht betroffen sehe, da wir da ja nur vergleichen, welche beiden Parteien in dem jeweiligen Jahr die meisten Stimmen bekommen haben (also die Gewinner-Parteien vergleichen und nicht absolute Stimmzahlen zwischen den Jahren).

Die größte Änderung berechnen wir jetzt prozentual basierend auf den gültigen Zweitstimmen.
