### ISSUE TITLE
Prozentzahlen haben zuviele Nachkommastellen

### ISSUE THREAD

**Issue by torfsen** [CodeforKarlsruhe/wahlkarte#6]
Wenn wir Prozentzahlen darstellen, dann sollten diese maximal 1 Nachkommastelle haben.

**Comment by hcorinna** [comment]
Ich geh mal davon aus, dass du [Ungültige Stimmen](https://codeforkarlsruhe.github.io/wahlkarte/#ungueltig) und [Kleinster Abstand](https://codeforkarlsruhe.github.io/wahlkarte/#kleinster-abstand) meinst, oder? Drei sind unschön, ja, aber da die Werte doch ziemlich klein sind, bin ich jetzt mal nur auf 2 Nachkommastellen runter.

**Comment by torfsen** [comment]
Gefixt in #9.
