### ISSUE TITLE
Statt "Größte Änderung" lieber "Größte Gewinner" und "Größte Verlierer"?

### ISSUE THREAD

**Issue by torfsen** [CodeforKarlsruhe/wahlkarte#7]
Die Ansicht [Größte Änderung](https://codeforkarlsruhe.github.io/wahlkarte/#aenderung) zeigt bisher diejenige Partei an, die im Vergleich zu 2013 die meisten Zweitstimmen hinzugewonnen hat (siehe dazu auch #5). Der Titel "Größte Änderung" ist also falsch, eigentlich werden die "Größten Gewinner" dargestellt.

Entweder sollten wir also tatsächlich die größte Änderung (positiv oder negativ) darstellen, oder (und das fände ich persönlich besser) wir benennen die Ansicht um in "Größte Gewinner" und fügen eine entsprechende Ansicht "Größte Verlierer" hinzu.

**Comment by hcorinna** [comment]
So wie ich das sehe, zeigen wir aktuell die betragsmäßig größte Änderung an (nicht den größten Gewinner), fände aber die Aufteilung in "Größter Gewinner" und "Größter Verlierer" spannender (vor allem da man aktuell eben auch nicht erkannt, ob die größte Änderung ein Gewinn oder Verlust ist und die Beschriftung des Szenarios irreführend ist).

**Comment by torfsen** [comment]
Gefixt in #9.
